
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.Data.ComprobantesManager.registrarPickingUser(RestServiceSabio.Model.Comprobante,RestServiceSabio.Model.Usuario)~System.Boolean")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.DbManager.DbConnection.open")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.Data.CodBarraManager.obtenerTodos~System.Collections.Generic.List{RestServiceSabio.Model.CodigoBarra}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.Data.ComprobantesManager.actualizarEstado(RestServiceSabio.Model.Comprobante)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.Data.ComprobantesManager.buscarIdSerial(System.Int64)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.Data.ComprobantesManager.existeSerial(System.Int64)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.Data.ComprobantesManager.guardarStock(RestServiceSabio.Model.Usuario,RestServiceSabio.Model.Comprobante)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.Data.ComprobantesManager.insertarDetalleMovArticulo(System.Int32,RestServiceSabio.Model.Item)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.Data.ComprobantesManager.insertarMovArticulo(RestServiceSabio.Model.Usuario,System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.Data.ComprobantesManager.insertarMovSerialesArt(System.Int32,System.Int32)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.Data.ComprobantesManager.insertarSeriales(System.Int64,System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.Data.ComprobantesManager.obtenerCodigoComprobante~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.Data.ComprobantesManager.obtenerComprobante(RestServiceSabio.Model.Usuario)~RestServiceSabio.Model.Comprobante")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.Data.ComprobantesManager.obtenerNumeroComprobante~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.DbManager.DbConnection.close")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.DbManager.DbManagerM.getGenerador(System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.DbManager.DbManagerM.getSiguienteGenerador(System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.DbManager.DbManagerM.insertSerialQuery(System.String,System.String,System.Object[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~M:RestServiceSabio.DbManager.DbManagerM.selectSimpleQuery(System.String,System.String,System.String,System.Object)~FirebirdSql.Data.FirebirdClient.FbDataReader")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~P:RestServiceSabio.Model.Comprobante.items")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~P:RestServiceSabio.Model.Comprobante.numeroPick")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~P:RestServiceSabio.Model.Comprobante.observaciones")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~P:RestServiceSabio.Model.Comprobante.orden")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~P:RestServiceSabio.Model.Comprobante.puedeUsuario")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~P:RestServiceSabio.Model.Item.cantidad")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~P:RestServiceSabio.Model.Item.codigoArticulo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~P:RestServiceSabio.Model.Item.descripcion")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~P:RestServiceSabio.Model.Item.kilos")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~P:RestServiceSabio.Model.Item.puedePickear")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~P:RestServiceSabio.Model.Item.saldo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~P:RestServiceSabio.Model.Item.seriales")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Estilo", "IDE1006:Estilos de nombres", Justification = "<Pendiente>", Scope = "member", Target = "~P:RestServiceSabio.Model.Item.unidad")]